src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $category_name;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="category_id")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategoryId($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategoryId() === $this) {
                $product->setCategoryId(null);
            }
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('category_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoriesController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categories")
 */
class CategoriesController extends AbstractController
{
    /**
     * @Route("", name="categories", methods={"GET"})
     */
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('categories/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    /**
     * @Route("/add", name="categories/add", methods={"GET", "POST"})
     */
    public function add(Request $request, CategoryRepository $categoryRepository): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            // Flash message
            $this->addFlash(
                'category_saved',
                'Category has been saved successfully !'
            );
            return $this->redirectToRoute('categories', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('categories/add.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/show/{id}", name="categories/show", methods={"GET"})
     */
    public function show(Category $category): Response
    {
        return $this->render('categories/show.html.twig', [
            'category' => $category,
        ]);
    }

    /**
     * @Route("edit/{id}", name="categories/edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categoryRepository->add($category, true);

            // Flash message
            $this->addFlash(
                'category_updated',
                'Category has been updated successfully !'
            );
            return $this->redirectToRoute('categories', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('categories/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    /**
     * @Route("delete/{id}", name="categories/delete", methods={"POST"})
     */
    public function delete(Request $request, Category $category, CategoryRepository $categoryRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $category->getId(), $request->request->get('_token'))) {
            $categoryRepository->remove($category, true);
        }

        // Flash message
        $this->addFlash(
            'category_removed',
            'Category has been removed successfully !'
        );
        return $this->redirectToRoute('categories', [], Response::HTTP_SEE_OTHER);
    }
}

templates/categories/_delete_form.html.twig
<form method="post" action="{{ path('categories/delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this category?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/categories/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categories/add.html.twig
{% extends 'default/base.html.twig' %}
{% block content %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Add a product category</div>
            <div class="panel-body">
                <div class="col-md-6">
                    {{ include('categories/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div><!-- /.col-->
{% endblock %}

templates/categories/edit.html.twig
{% extends 'default/base.html.twig' %}
{% block content %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Update a product category</div>
            <div class="panel-body">
                <div class="col-md-6">
                    {{ include('categories/_form.html.twig', {'button_label': 'Update'}) }}
                </div>
            </div>
        </div>
    </div><!-- /.col-->

    {{ include('categories/_delete_form.html.twig') }}
{% endblock %}

templates/categories/index.html.twig
{% extends '/default/base.html.twig' %}
{% block content %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Product categories</div>
            <div class="panel-body">
                <!-- Flash messages -->
                {% for messages in app.flashes(['category_saved', 'category_updated', 'category_removed']) %}
                    {% for message in messages %}
                        <p class="alert alert-success w-100 h-100">
                            {{ message }}
                        </p>
                    {% endfor %}
                {% endfor %}

                <a href="{{ path('categories/add') }}" class="btn btn-primary">New</a>
                <table data-toggle="table" data-url="" data-show-refresh="true" data-show-toggle="true"
                       data-show-columns="true" data-search="true" data-select-item-name="toolbar1"
                       data-pagination="true"
                       data-sort-name="name" data-sort-order="desc">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Category name</th>
                        <th>Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for category in categories %}
                        <tr>
                            <td>{{ category.id }}</td>
                            <td>{{ category.categoryName }}</td>
                            <td>
                                <div class="card-footer">
                                    <a href="{{ path('categories/show', {'id': category.id}) }}"
                                       class="btn btn-default">Show details</a>
                                    <a href="{{ path('categories/edit', {'id': category.id}) }}"
                                       class="btn btn-primary">Edit</a>
                                    <form method="post" action="{{ path('categories/delete', {'id': category.id}) }}"
                                          onsubmit="return confirm('Are you sure you want to remove {{ category.categoryName }} ?');">
                                        <input type="hidden" name="_token"
                                               value="{{ csrf_token('delete' ~ category.id) }}">
                                        <button class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/categories/show.html.twig
{% extends 'default/base.html.twig' %}
{% block content %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Show product category</div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ category.id }}</td>
                    </tr>
                    <tr>
                        <th>Category Name</th>
                        <td>{{ category.categoryName }}</td>
                    </tr>
                    </tbody>
                </table>
                <a href="{{ path('categories') }}">Back to list</a>
            </div>
        </div>
    </div>
{% endblock %}